### ISSUE TITLE
Null Pointer on Launch

### ISSUE THREAD

**Issue by BoClow** [rsmith52/Testing-Data-Analyzer#4] opened 2019-04-26 19:13 UTC
Severity: Blocker
Description: Upon launching the app and running Main.java as instructed in Eclipse, we receive a null pointer immediately after “Hello, Welcome to Data Analyzer for DoIT” is printed. Can be resoled by adding empty folders “pdf” and “cats” in the project directory. We suggest you keep a place holder file in these directories to keep them from being removed in git.

**Comment by rsmith52** [comment] 2019-05-01 02:43
This was caused by pdf and cats folders not existing, which is now fixed and has a Temp file to make sure they always exist

**Closed as completed by rsmith52** 2019-05-01 02:43 UTC
